version: '3.8'

services:
  book:
    build: ./services/book
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  customer:
    build: ./services/customer
    ports:
      - "3001:3001"
    depends_on:
      - mongo

  order:
    build: ./services/order
    ports:
      - "3002:3002"
    depends_on:
      - mongo
      - book
      - customer
  mongo:
    image: mongo:4.4.6
    ports:
      - "27017:27017"
    volumes:
      - data-db:/data/db

volumes:
  data-db:
